// <auto-generated />
using Blazor.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazor.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230520085329_MoreProducts")]
    partial class MoreProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blazor.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SandBox",
                            Url = "sandboxs"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Simulation",
                            Url = "simulations"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Survival",
                            Url = "survivals"
                        },
                        new
                        {
                            Id = 4,
                            Name = "RPG",
                            Url = "RPGs"
                        });
                });

            modelBuilder.Entity("Blazor.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            Description = "Don't Starve is a survival video game developed by the Canadian indie video game developer Klei Entertainment.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/d2/Don%27t_Starve_cover.jpg",
                            Price = 9.9m,
                            Title = "Don't Starve"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Stardew Valley is a simulation role-playing video game developed by Eric 'ConcernedApe' Barone.",
                            ImageUrl = "https://thumbnails.pcgamingwiki.com/1/1b/Stardew_Valley_cover.png/300px-Stardew_Valley_cover.png",
                            Price = 9.9m,
                            Title = "Stardew Valley"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Minecraft is a sandbox game developed by Mojang Studios.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/5/51/Minecraft_cover.png",
                            Price = 9.9m,
                            Title = "Minecraft"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "A variety of Sims are yours to personalize, each with distinct appearances, dynamic personalities, and inspiring aspirations.",
                            ImageUrl = "https://m.media-amazon.com/images/I/71otyq1xFNL._AC_SY500_.jpg",
                            Price = 9.9m,
                            Title = "Sims4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Originally created by legendary game designer Sid Meier, Civilization is a turn-based strategy game in which you attempt to build an empire to stand the test of time. Explore a new land, research technology, conquer your enemies, and go head-to-head with history’s most renowned leaders as you attempt to build the greatest civilization the world has ever known.",
                            ImageUrl = "https://image.api.playstation.com/vulcan/img/cfn/11307KFcs3gBlcheONy-ZOYZ5kplFnq5jXinUSI8HkCc8P2gdI1_32JrKJ-vxns32LjXBcQteG2EOwuzWS_KXqE5VCYFmS4Z.png",
                            Price = 9.9m,
                            Title = "Civilization6"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Description = "Bethesda Game Studios' blockbuster open-world RPG puts players on the precipice of determining the future of Skyrim as the Empire waits for the prophesized Dragonborn to come; a hero born with the power of The Voice, and the only one who can stand amongst the dragons.",
                            ImageUrl = "https://assets-prd.ignimgs.com/2021/08/19/elder-scrolls-skyrim-button-2017-1629409446732.jpg",
                            Price = 9.9m,
                            Title = "The Elder Scrolls 5: Skyrim"
                        });
                });

            modelBuilder.Entity("Blazor.Shared.Product", b =>
                {
                    b.HasOne("Blazor.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
